<?php

namespace Database\Seeders;

use App\Models\State;
use Illuminate\Database\Seeder;

class StatesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $item = new State();
        $item->name = "Alabama";
        $item->abbreviation = "AL";
        $item->save();
        $item = new State();
        $item->name = "Alaska";
        $item->abbreviation = "AK";
        $item->save();
        $item = new State();
        $item->name = "American Samoa";
        $item->abbreviation = "AS";
        $item->save();
        $item = new State();
        $item->name = "Arizona";
        $item->abbreviation = "AZ";
        $item->save();
        $item = new State();
        $item->name = "Arkansas";
        $item->abbreviation = "AR";
        $item->save();
        $item = new State();
        $item->name = "California";
        $item->abbreviation = "CA";
        $item->save();
        $item = new State();
        $item->name = "Colorado";
        $item->abbreviation = "CO";
        $item->save();
        $item = new State();
        $item->name = "Connecticut";
        $item->abbreviation = "CT";
        $item->save();
        $item = new State();
        $item->name = "Delaware";
        $item->abbreviation = "DE";
        $item->save();
        $item = new State();
        $item->name = "District of Columbia";
        $item->abbreviation = "DC";
        $item->save();
        $item = new State();
        $item->name = "Florida";
        $item->abbreviation = "FL";
        $item->save();
        $item = new State();
        $item->name = "Georgia";
        $item->abbreviation = "GA";
        $item->save();
        $item = new State();
        $item->name = "Guam";
        $item->abbreviation = "GU";
        $item->save();
        $item = new State();
        $item->name = "Hawaii";
        $item->abbreviation = "HI";
        $item->save();
        $item = new State();
        $item->name = "Idaho";
        $item->abbreviation = "ID";
        $item->save();
        $item = new State();
        $item->name = "Illinois";
        $item->abbreviation = "IL";
        $item->save();
        $item = new State();
        $item->name = "Indiana";
        $item->abbreviation = "IN";
        $item->save();
        $item = new State();
        $item->name = "Iowa";
        $item->abbreviation = "IA";
        $item->save();
        $item = new State();
        $item->name = "Kansas";
        $item->abbreviation = "KS";
        $item->save();
        $item = new State();
        $item->name = "Kentucky";
        $item->abbreviation = "KY";
        $item->save();
        $item = new State();
        $item->name = "Louisiana";
        $item->abbreviation = "LA";
        $item->save();
        $item = new State();
        $item->name = "Maine";
        $item->abbreviation = "ME";
        $item->save();
        $item = new State();
        $item->name = "Maryland";
        $item->abbreviation = "MD";
        $item->save();
        $item = new State();
        $item->name = "Massachusetts";
        $item->abbreviation = "MA";
        $item->save();
        $item = new State();
        $item->name = "Michigan";
        $item->abbreviation = "MI";
        $item->save();
        $item = new State();
        $item->name = "Minnesota";
        $item->abbreviation = "MN";
        $item->save();
        $item = new State();
        $item->name = "Mississippi";
        $item->abbreviation = "MS";
        $item->save();
        $item = new State();
        $item->name = "Missouri";
        $item->abbreviation = "MO";
        $item->save();
        $item = new State();
        $item->name = "Montana";
        $item->abbreviation = "MT";
        $item->save();
        $item = new State();
        $item->name = "Nebraska";
        $item->abbreviation = "NE";
        $item->save();
        $item = new State();
        $item->name = "Nevada";
        $item->abbreviation = "NV";
        $item->save();
        $item = new State();
        $item->name = "New Hampshire";
        $item->abbreviation = "NH";
        $item->save();
        $item = new State();
        $item->name = "New Jersey";
        $item->abbreviation = "NJ";
        $item->save();
        $item = new State();
        $item->name = "New Mexico";
        $item->abbreviation = "NM";
        $item->save();
        $item = new State();
        $item->name = "New York";
        $item->abbreviation = "NY";
        $item->save();
        $item = new State();
        $item->name = "North Carolina";
        $item->abbreviation = "NC";
        $item->save();
        $item = new State();
        $item->name = "North Dakota";
        $item->abbreviation = "ND";
        $item->save();
        $item = new State();
        $item->name = "Northern Mariana Islands";
        $item->abbreviation = "MP";
        $item->save();
        $item = new State();
        $item->name = "Ohio";
        $item->abbreviation = "OH";
        $item->save();
        $item = new State();
        $item->name = "Oklahoma";
        $item->abbreviation = "OK";
        $item->save();
        $item = new State();
        $item->name = "Oregon";
        $item->abbreviation = "OR";
        $item->save();
        $item = new State();
        $item->name = "Pennsylvania";
        $item->abbreviation = "PA";
        $item->save();
        $item = new State();
        $item->name = "Rhode Island";
        $item->abbreviation = "RI";
        $item->save();
        $item = new State();
        $item->name = "South Carolina";
        $item->abbreviation = "SC";
        $item->save();
        $item = new State();
        $item->name = "South Dakota";
        $item->abbreviation = "SD";
        $item->save();
        $item = new State();
        $item->name = "Tennessee";
        $item->abbreviation = "TN";
        $item->save();
        $item = new State();
        $item->name = "Texas";
        $item->abbreviation = "TX";
        $item->save();
        $item = new State();
        $item->name = "Utah";
        $item->abbreviation = "UT";
        $item->save();
        $item = new State();
        $item->name = "Vermont";
        $item->abbreviation = "VT";
        $item->save();
        $item = new State();
        $item->name = "Virgin Islands";
        $item->abbreviation = "VI";
        $item->save();
        $item = new State();
        $item->name = "Virginia";
        $item->abbreviation = "VA";
        $item->save();
        $item = new State();
        $item->name = "Washington";
        $item->abbreviation = "WA";
        $item->save();
        $item = new State();
        $item->name = "West Virginia";
        $item->abbreviation = "WV";
        $item->save();
        $item = new State();
        $item->name = "Wisconsin";
        $item->abbreviation = "WI";
        $item->save();
        $item = new State();
        $item->name = "Wyoming";
        $item->abbreviation = "WY";
        $item->save();
    }
}
